spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost/notifikasidb
    username: notifikasiuser
    password: notifikasi01
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  jackson:
    serialization:
      indent-output: true
  kafka:
      bootstrap-servers: kafka2.tazkia.ac.id:9092
      consumer:
        group-id: appnotification
        auto-offset-reset: earliest

template:
  email:
    basedir: templates/email

kafka:
  topic:
    notification: notification
    email: mail-notification
    sms: sms-notification

logging:
  level:
    id.ac.tazkia: DEBUG